divert(-1)
changequote(`[',`]')
define([dc_title_short], [tool])
define([dc_title_mac],[$1($2)])
define([dc_title], [dc_title_short])
define([dc_title_alternative], [Tool Name Man Page])
define([ndc_doc_number],[6734])
define([dc_title_subtitle], [Document Template])
define([dc_keyword_1], [software])
define([dc_keyword_2], [manpage])
define([dc_keyword_3], [template])
define([dc_keyword_4], [])
define([dc_keyword_5], [])
define([dc_keyword_6], [])
define([dc_keywords], [dc_keyword_1, dc_keyword_2, dc_keyword_3, dc_keyword_4, dc_keyword_5, dc_keyword_6])
define([dc_subject], [N/A])
define([dc_description], [|
    The *man pages*, short for *reference manual pages*,
    are your keys to Linux.
    Everything you want to know is there – take it all in and run with it.
    The collection of documents will never win a Pulitzer prize,
    but the set is quite accurate and complete.
    The man pages are *the* primary source,
    and that authority is well-known.])
define([dc_description_abstract], [The *man pages*, short for *reference manual pages*, are your keys to Linux.])
define([dc_description_note], [(N/A)])
define([dc_description_release], [(N/A)])
define([dc_description_tableOfContents], [(N/A)])
define([dc_type], [text/markdown; charset=UTF-8])
define([dc_source], [https://github.com/markj1069/templates-J70413419/tree/master/doc/X77-6734/V01])
define([dc_relation], [02.00.01])
define([dc_relation_isVersionOf], [(N/A)])
define([dc_relation_hasVersion], [(N/A)])
define([dc_relation_isReplacedBy], [(N/A)])
define([dc_relation_replaces], [(N/A)])
define([dc_relation_requires], [(N/A)])
define([dc_relation_isPartOf], [(N/A)])
define([dc_relation_hasPart], [(N/A)])
define([dc_relation_isReferencedBy], [(N/A)])
define([dc_relation_references], [(N/A)])
define([dc_relation_isFormatOf], [(N/A)])
define([dc_relation_hasFormat], [(N/A)])
define([dc_relation_conformsTo], [(N/A)])
define([dc_coverage], [(N/A)])
define([dc_creator], [Mark J. Jensen])
define([ndc_creator_email], [mark@jensen.net])
define([dc_creator_family], [Jensen])
define([dc_creator_given], [Mark J.])
define([dc_creator_jobTitle], [Independent Scholar])
define([dc_publisher], [Mark J. Jensen])
define([dc_contributor], [(N/A)])
define([dc_contributor_role], [(N/A)])
define([dc_rights], [CC BY 4.0])
define([dc_rights_accessRights], [See license.])
define([dc_rights_license], [https://creativecommons.org/licenses/by/4.0/legalcode])
define([dc_date], [2025-03-23])
define([dc_date_accepted], [YYYY-MM-DD])
define([dc_date_created], [2025-03-23])
define([dc_date_dateAccepted], [YYYY-MM-DD])
define([dc_date_dateCopyrighted], [YYYY-MM-DD])
define([dc_date_dateSubmitted], [YYYY-MM-DD])
define([dc_date_valid], [YYYY-MM-DD])
define([dc_date_available], [2025-03-23])
define([dc_date_issued], [YYYY-MM-DD])
define([dc_date_modified], [YYYY-MM-DD])
define([dc_format], [Man Page])
define([dc_format_extent], [(N/A)])
define([dc_format_medium], [AsciiDoc])
define([dc_identifier], [X77-ndc_doc_number-01])
define([dc_identifier_bibliographicCitation], [(N/A)])
define([dc_identifier_doc], [X77-ndc_doc_number-01])
define([dc_identifier_func], [Template])
define([ndc_identifier_type], [Man Page])
define([dc_identifier_proj], [J70413419])
define([ndc_identifier_proj_name],[Document Templates])
define([dc_language], [en-US])
define([dc_accrualMethod], [Item Creation])
define([dc_accrualPeriodicity], [(N/A)])
define([dc_accrualPolicy], [(N/A)])
define([dc_audience], [Other]) # Select appropriate items.
define([dc_audience_educationLevel], [(N/A)]) # Select education levels.
define([dc_instructionalMethod], [(N/A)])
define([dc_provenance], [Item Creation])
define([dc_rightsHolder], [Mark J. Jensen])
define([dc_creator_sig], dc_creator)
define([ndc_creator_address_1],[8651 Stephens Church Rd # D-108])
define([ndc_creator_address_2],[(N/A)])
define([ndc_creator_city],[Wilmington])
define([ndc_creator_st],[NC])
define([ndc_creator_zip],[28411-7982])
define([ndc_to],[[To]])
define([ndc_to_address_1],[[To Address 1]])
define([ndc_to_address_2],[[To Address 1]])
define([ndc_to_city],[[To City]])
define([ndc_to_st],[[To State]])
define([ndc_to_zip],[[To Zip]])
define([ndc_letter_date],[[Letter Date]])
define([ndc_salutation],[[Dear To]])
define([ndc_closing],[Sincerly yours])
define([dnc_cc],[(N/A)])
define([dnc_cc_1],[(N/A)])
define([dnc_cc_2],[(N/A)])
define([dnc_cc_3],[(N/A)])
define([dnc_cc_4],[(N/A)])
define([dnc_cc_5],[(N/A)])
define([dnc_cc_6],[(N/A)])
define([dnc_enc],[(N/A)])
define([dnc_enc_1],[(N/A)])
define([dnc_enc_2],[(N/A)])
define([dnc_enc_3],[(N/A)])
define([dnc_enc_4],[(N/A)])
define([dnc_enc_5],[(N/A)])
define([dnc_enc_6],[(N/A)])
changequote()
divert(0)dnl
